server:
  port: 8711

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: productService
          uri: http://localhost:8721
          predicates:
            - Path=/product/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

